RNN的简单实现


In [4]:
import os
import numpy as np
import tensorflow as tf

In [5]:
n_inputs = 3
n_units = 5


In [7]:
x0 = tf.placeholder(tf.float32,[None,n_inputs])
x1 = tf.placeholder(tf.float32,[None,n_inputs])

In [14]:
Wx = tf.Variable(tf.random_normal([n_inputs,n_units],dtype=tf.float32),name='Wx')
Wh = tf.Variable(tf.random_normal([n_units,n_units],dtype=tf.float32),name='Wh')
b = tf.Variable(tf.zeros([n_units,],dtype=tf.float32),name='b')

h0 = tf.tanh(tf.matmul(x0,Wx) + b)
h1 = tf.tanh(tf.matmul(x1,Wx) + tf.matmul(h0,Wh) + b)

init = tf.global_variables_initializer()

x0_batch = np.array([[0,1,2],[3,4,5],[6,7,8],[9,0,5]])
x1_batch = np.array([[0,1,0],[9,8,7],[6,5,4],[3,2,1]])

In [15]:
with tf.Session() as sess:
    sess.run(init)
    h0_val, h1_val = sess.run([h0, h1], feed_dict={x0: x0_batch, x1: x1_batch})
print('the output of h0_val is')
print(h0_val)
                               
print('the output of h1_val is ')
print(h1_val)

the output of h0_val is
[[-0.49205106  0.9896048  -0.9256854   0.9986742  -0.94364953]
 [ 0.04766949 -0.8186476  -0.99956566  0.99971724 -0.99960726]
 [ 0.56092024 -0.99989605 -0.9999977   0.99993974 -0.99999726]
 [-0.06303429 -1.         -0.9999308  -0.99986166 -1.        ]]
the output of h1_val is 
[[-0.998887   -0.9992335   0.6414366   0.92284864  0.06409429]
 [ 0.8844261  -1.         -0.99996793 -0.8448331  -0.9999883 ]
 [ 0.4508441  -1.         -0.99457175 -0.98451877 -0.9973781 ]
 [-0.05041267 -0.9993623  -0.999677   -0.99914885  0.94515145]]
